version: "3.9"

services:
  database_todo:
    image: postgres
    container_name: todo_database
    restart: always
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=mobicare
      - POSTGRES_PASSWORD=mobicare
      - POSTGRES_DB=mobicare
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
