version: "3.9"

services:
  database_todo:
    image: postgres
    container_name: todo_database
    restart: always
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=mobicare
      - POSTGRES_PASSWORD=mobicare
      - POSTGRES_DB=mobicare
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: todo_nodejs
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
